// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// URL atualizada conforme fornecido pelo usuário
const SUPABASE_URL = "https://pohcuxyzdfctfpppnvxa.supabase.co";

// ATENÇÃO: Esta chave abaixo pertence ao projeto antigo. 
// Ela precisa ser substituída pela Anon Key do projeto pohcuxyzdfctfpppnvxa para funcionar.
const SUPABASE_PUBLISHABLE_KEY = "SUBSTITUA_PELA_NOVA_ANON_KEY_AQUI";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);