// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dwgccyrtmjaquufbkfhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3Z2NjeXJ0bWphcXV1ZmJrZmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMTc2MzMsImV4cCI6MjA4Nzc5MzYzM30.G27GNmK8u4WuoZne1rf8EmfBjYqq7m_ArrRXx1EKxh8";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);